# Generated by Django 4.2.6 on 2023-10-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pin_code',
            new_name='zip_code',
        ),
    ]
